version: '3'
services:
    todo:
        build:
            context: .
            dockerfile: docker/todo.dockerfile
        ports:
            - "9090:80"
            - "9091:9000"
        volumes:
            - ./docker/wiki.nginx.conf:/etc/nginx/conf.d/default.conf
            - vendor:/var/www/vendor
            - ./src:/var/www
        depends_on:
            - mysql
    wiki:
        build:
            context: .
            dockerfile: docker/wiki.dockerfile
        ports:
            - "7070:80"
            - "7071:9000"
        volumes:
            - ./docker/wiki.nginx.conf:/etc/nginx/conf.d/default.conf
            - vendor:/var/www/vendor
            - ./src:/var/www
        depends_on:
            - mysql
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'avocado'
        volumes:
            - mysqldata:/var/lib/mysql
            - ./docker/sql:/docker-entrypoint-initdb.d
        ports:
            - 7706:3306
volumes:
    mysqldata: {}
    vendor:
