# fly.toml app configuration file generated for wiki-srv on 2023-12-13T14:28:57-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wiki-srv"
primary_region = "sjc"

[build]
  dockerfile = "./docker/wikisrv.fly.dockerfile"

[env]
  DB_HOST = "mysql-srv.internal"
  DB_NAME = "wiki"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
